### ISSUE TITLE
スケール崩壊?

### ISSUE THREAD

**Issue by tamaina** [wa-st/pak-nippon#1]
はじめまして、tamaina と申します。
いつもpak.nippon を使わせて頂いています。
私は、このpakの統一された世界がとても大好きです。

そこで、提案なのですが、スケールをもう少し統一したら如何でしょうか。
とくに、新しく追加されたニトリのスロープの幅が一車線分しかなく、気になっています。
3*3マスに合わせるための苦肉の策だとは思うのですが・・・

修正できたらでいいのでよろしくお願いします。
![slope](https://cloud.githubusercontent.com/assets/7973572/7333601/a68d199e-ebb0-11e4-8039-29965e10cac0.PNG)

**Comment by wa-st** [comment]
はじめまして、こんにちは。
返事が大変遅くなってしまい、申し訳ありません。

pak.nipponのスケールについてですが、ゲームバランスや互換性を維持しながらアドオンを作るためには、どうしても小さなタイルに大きな建物を詰め込む必要があり、スケールの不統一は避けられないものだと考えています。
無理にスケールを揃えようとしても、別の部分にシワ寄せが出てくるだけなので、pak.nipponではスケールの統一を最初から諦めています。ごめんなさい。

とはいえ、ニトリのスロープに違和感があるのはご指摘のとおりなので、可能な範囲で修正をしてみました。3x3マスに収まる範囲でスロープの幅をなるべく広げてみたつもりですが、いかがなものでしょうか。

![ss](https://cloud.githubusercontent.com/assets/5622308/7445636/81c96a12-f1f6-11e4-8a6b-011df9e901ea.png)
![z-map](https://cloud.githubusercontent.com/assets/5622308/7445637/81c9e028-f1f6-11e4-9dcf-1e56fd94d93a.png)

**Comment by tamaina** [comment]
> ゲームバランスや互換性を維持しながらアドオンを作るためには、どうしても小さなタイルに大きな
> 建物を詰め込む必要があり、スケールの不統一は避けられないものだと考えています。
> pak.nipponではスケールの統一を最初から諦めています。ごめんなさい。

そうですよね。やっぱり、妥協に妥協を重ねてこうなってるんですよね・・・

修正案ですが、これでいいと思います。無理のない範囲で修正できていますし。

たぶんこれからも気になるところは口出しすると思うので、よろしくお願いします。

ちなみに、「こんな建物を作って欲しい」とかの要望って受け付けてますか？
いわゆるクレクレってやつですけれど。ご返答をお待ちしています。
_できたとしたら、出来る限り資料の写真は集めようと思います!_

**Comment by wa-st** [comment]
> たぶんこれからも気になるところは口出しすると思うので、よろしくお願いします。

自分以外の視点はとても参考になります。こちらこそよろしくお願いします。

> ちなみに、「こんな建物を作って欲しい」とかの要望って受け付けてますか？

必ず作るとは約束できませんが、自分のできる範囲で要望には応えたいと思います。

アドオン作成の基準として、
- pak64用の乗り物アドオンと互換性を維持するため、貨物・産業の構成はおおむねpak64に従う
- 産業・ランドマークのサイズは4x4マス以下
- 市内建築物のレベルは最大30
- 箱積み駅舎・景観線路などSimutrans本体の機能から外れたアドオンはPakset本体には取り込まない。仮にそれらを作成する場合は、Pakset本体とは別に配布する

などのルールが今の自分の頭の中になんとなく存在するので、実際にアドオンを作る際には、この基準に沿ったものになろうかと思います。

要望を出していただくのであれば、グーグルのストリートビューに映っている建物にしていただけるとうれしいです。アドオン作成の資料は、グーグルマップやBing Mapsの空中写真とストリートビューが１番便利ですので。
（現存しない建物、変わった立地の建物であれば、ストリートビューで見られなくても仕方ありませんが……）

**Comment by wa-st** [comment]
一方的にcloseしたら不味かった気がするので、しばらくopen。
