### ISSUE TITLE
プライオリティシグナル(色灯式)の縦に2つ並んだ信号機に違和感を感じる

### ISSUE THREAD

**Issue by soukouki** [wa-st/pak-nippon#13]
v0.4.0リリースお疲れ様です。

プライオリティシグナル(色灯式)の縦に2つ並んだ信号機に違和感を感じます。

**Comment by wa-st** [comment]
こんばんは。

代わりのデザインをいくつか考えてみましたが、どうでしょうか？

「このデザインがいい」とか「もっとこうした方がいい」とか
教えて頂けるとありがたいです。

![temp](https://user-images.githubusercontent.com/5622308/48072238-6586d980-e21f-11e8-940b-434728c60030.png)

**Comment by soukouki** [comment]
おつかれさまです。

- 赤
  - 赤は停止のイメージがあるので、少し微妙な気が・・自分だけかな？
- 白
  - 画面の色調を変えるソフトとかで見分けがつきにくい人もいるので、避けたほうがいいのでは
- 黄の上に黒
  - プレシグナルとの見分けが付きにくいので、避けたほうがいいのでは
- 黒
  - 悪くないと思います・・
- 4灯、5灯
  - 思ったよりも普通の信号との見分けが付きにくいので、避けたほうがいいのでは

青色とか見分けが付きやすいので、試してみてもいいのでは、と思います

**Comment by wa-st** [comment]
青は個人的に微妙なので、黒にしてみました。

**Comment by soukouki** [comment]
対応ありがとうございます。
