### ISSUE TITLE
道路信号機バグ

### ISSUE THREAD

**Issue by Ranran-the-JuicyPork** [wa-st/pak-nippon#14]
(´・ω・｀)v0.6.0で道路信号機が交差点以外の道路上どこにでも設置でき、かつ画像が表示されなくなっていると思います

**Comment by wa-st** [comment]
リリースしたファイル（roadsign.np-road.pak）に間違いがあったようなので、修正版（v0.6.1）をアップしました。
ご報告ありがとうございました。
