### ISSUE TITLE
v6.0.1において鉄道用信号機が表示されない状況です

### ISSUE THREAD

**Issue by karinntokarinnto** [wa-st/pak-nippon#15]
はじめまして。かりんとうと申します。

さて表題の件ですが、v6.0.1において、鉄道信号の一切が、設置はできるものの表示されないという事象が発生しております。設置したマスを調査ツールでクリックすると信号の情報が出てくるが、描画がされないという状況です。

私以外の他の方でも同様の事象が起こっているようで、恐らくpak.nippon側に原因があると推察されるため報告させていただきます。
ぜひご対応のほどよろしくお願い致します。

**Comment by wa-st** [comment]
はじめまして。こんにちは。

roadsign.np-rail.pak, roadsign.np-monorail.pakもリリースしたファイルに
間違いがあったようなので、修正版（v0.6.2）をアップしました。

リリース作業にミスが多く大変申し訳ありません。
ご報告ありがとうございました。
