### ISSUE TITLE
【製作依頼】低層現代商業ビル

### ISSUE THREAD

**Issue by tamaina** [wa-st/pak-nippon#2]
高崎の画像みたいな感じの商店が使いやすく、量産しやすく、日本らしいと思うので、ぜひnipponで作って欲しいです。よろしくお願いします。
Levelは13くらい(半端)かな
nippon風に名前をつけるとしたら低層現代商業ビル？

https://www.google.co.jp/maps/@36.324916,139.010168,3a,90y,254.91h,96.25t/data=!3m4!1e1!3m2!1s6UZ6I01MBHEaol8YnT8YXw!2e0?hl=ja
![takasaki03](https://cloud.githubusercontent.com/assets/7973572/7489928/cbffb68c-f416-11e4-93f2-c52f84a59607.PNG)
![takasaki04](https://cloud.githubusercontent.com/assets/7973572/7489931/cc075ac2-f416-11e4-8827-5bae246390c4.PNG)
https://www.google.co.jp/maps/@36.324093,139.010248,3a,90y,77.45h,96.82t/data=!3m4!1e1!3m2!1sqGSuvy4wFIA_bjsoDM3c9Q!2e0?hl=ja
![takasaki01](https://cloud.githubusercontent.com/assets/7973572/7489929/cc0134bc-f416-11e4-8497-d1eac8af9761.PNG)
https://www.google.co.jp/maps/@36.324461,139.010245,3a,90y,266.16h,99.15t/data=!3m4!1e1!3m2!1stPbphOx8yyTPRun6ZciCeQ!2e0?hl=ja
![takasaki02](https://cloud.githubusercontent.com/assets/7973572/7489930/cc045516-f416-11e4-9b65-8dfeeea2ae0d.PNG)

**Comment by wa-st** [comment]
了解です。

**Comment by tamaina** [comment]
おお、すごい！ありがとうございます！
