### ISSUE TITLE
wa様へのお願い事項

### ISSUE THREAD

**Issue by cacapo2501** [wa-st/pak-nippon#3]
突然のご連絡失礼します。
私はpak64.hitotoseという新規pakset開発メンバーのcacapo2501ことTakamaroと申します。

さて表題の件についてですが、開発メンバーからpak64.hitotoseの新規からの作り込みを断念し、pak.nipponの追加アドオンセットとして、再出発してはどうか、という案が上がりました。

比較的大きなアドオンセットとして、pak.nipponに依存するものを作成したいと考えております。

おおまかな概要については以下の通りです。
・pak.nipponの世界観を壊さない車両アドオン作り
・デフォルトのpak64車両よりも大型化された車体（鉄道以外も含む）
・リアルな編成を組める設定
・開発はEDGE2他によるドット絵方式で行います。
・必要であればサンプルをおつけしますので、コメントいただければ幸いです。

つきましてはMITライセンスのpak.nipponの件で承認をいただくのはお手数かと思いますが、
pak.nipponをベースとしたアドオンセットの作成を行ってもよろしいでしょうか？

フォーラムの掲示板にも上げさせていただきましたが、こちらに再度掲載させていただきました。

お手数おかけしますが何卒宜しくお願い致します。

**Comment by wa-st** [comment]
はじめまして。こんにちは。
フォーラムの書き込みにまったく気が付かず申し訳ありません。

pak.nipponのうちwaの作成した部分については、煮るなり焼くなり自由にしていただいて構いません。派生アドオンセットの作成ももちろんOKです。

ただ、Pak64のアドオンをそのまま利用している部分や、りむ氏が作成された「日本風左側通行信号機セット」に由来する部分については、MITライセンスではありませんので、それぞれのライセンス／readmeをご確認の上、ご利用下さい。

いいかげんな制作スタイルのpak.nipponですが、新アドオンセットの作成に少しでもお役に立てれば幸いです。

**Comment by cacapo2501** [comment]
ご回答と許可ありがとうございます。
製作させていただきます。
