### ISSUE TITLE
【制作依頼】立体な駐車場

### ISSUE THREAD

**Issue by tamaina** [wa-st/pak-nippon#4]
駐車場が平面だけだと少し物足りないので、鉄骨のごつい立駐が欲しい時代が私にもありました。
1.市内建築・・・以下のラインナップでいかがでしょう
・タワーパーキング(中が見えて動くとSo good(無茶))
・多段式パーキング
・地下駐車場入口
2.特殊建築
・自走式
　4マス~9マスで2階、3階、5階、10階建て
　階数が少ないほど面積が大きくて古臭い感じでしょうか。

諸事情で参考画像は後で上げさせていただきます。以上ご精査よろしくお願いします。

**Comment by tamaina** [comment]
参考画像どうぞ↓
https://www.dropbox.com/s/5otcodu8auxi1pb/npan.zip?dl=0
タワーパーキングと多段式は入ってません。
5階建ての自走式立体駐車場ってなかなかないですね・・・
ファイル名をgooglemapの座標にしてあります。https://www.google.co.jp/maps/@座標とすれば一瞬で出てきます。

**Comment by wa-st** [comment]
だいたい了解ですが、「2.特殊建築」というのは「ランドマーク」ではなく「特別建築物」のことで大丈夫でしょうか。

**Comment by tamaina** [comment]
私は特殊建築="Type=cur"って意味で使ってます。わかりづらくて申し訳ないです。

**Comment by wa-st** [comment]
レスありがとうございます。"Type=cur"で進めます。

↓途中経過（背の高い駐車場などはこれから作ります）
![output](https://cloud.githubusercontent.com/assets/5622308/9309982/f14f6cf2-4547-11e5-8b10-00f51e19a82b.png)

**Comment by tamaina** [comment]
わーお！いいっすねぇ！

**Comment by tamaina** [comment]
ありがとうございました！
これで駅前SSが捗りますw
