### ISSUE TITLE
線路について

### ISSUE THREAD

**Issue by tamaina** [wa-st/pak-nippon#5]
線路のソースファイル(Gimpのやつ)は公開されないのでしょうか？
それともgimpではなく3DCGで作ってるのでしょうか？

nippon版の景観線路を作りたいので・・・

**Comment by wa-st** [comment]
pak.nipponの線路は3Dで作成しているので、元となるGimpファイルはありません。

GIMPで１から作ったアドオンは、リポジトリのimgフォルダに元データを
すべて置くようにしているので、それ以外の公開していないGimpファイルは
(中間作業用のファイルなどを除いて)無いはずです。

景観線路の方ですが、それに近いような近くないようなことを途中まで試作して
そのまま放置中のデータがあったので、参考までにどうぞ。
![track-1](https://cloud.githubusercontent.com/assets/5622308/9910778/bec23b12-5cd9-11e5-9f18-ba05e740af05.png)
![track-2](https://cloud.githubusercontent.com/assets/5622308/9910779/becc3d2e-5cd9-11e5-8561-3b910637befb.png)
![track-3](https://cloud.githubusercontent.com/assets/5622308/9910780/bece1fb8-5cd9-11e5-97c0-b9827333b941.png)
![track-4](https://cloud.githubusercontent.com/assets/5622308/9910781/bece5ece-5cd9-11e5-888a-1839daa58c1c.png)

**Comment by tamaina** [comment]
あー、純正の列車が通ったとおりにポイントが切り替わるやつですねー
とりあえず借りときます。ありがとうございます。

うーん、あとせめてものお願いで高架の線路なし(できれば、手前と奥 / 壁と梁と柱も分けて)単品で欲しいっす。

---

_じつは線路が黒いのは錆びてる感じがしてあんま好きじゃなかったり。(幹線級は)テカテカしてたほうが、高頻度な感じでこのみ_

**Comment by wa-st** [comment]
長く放置してしまい誠に申し訳ないです。

![elv-frame-back](https://cloud.githubusercontent.com/assets/5622308/10417993/7f3e5912-7089-11e5-9f6a-ce4f7d046871.png)　![elv-frame-center](https://cloud.githubusercontent.com/assets/5622308/10417994/7f3fe048-7089-11e5-8d60-98da2eaa8cb2.png)
![elv-frame-front](https://cloud.githubusercontent.com/assets/5622308/10417992/7f3d4f86-7089-11e5-9f04-88015efa0d14.png)　![elv-frame-single](https://cloud.githubusercontent.com/assets/5622308/10417995/7f421d4a-7089-11e5-9765-7b5487e5fc53.png)

ここまではできましたが、壁／梁／柱の分離とかは面倒くさいので勘弁してください。

> じつは線路が黒いのは錆びてる感じがしてあんま好きじゃなかったり。(幹線級は)テカテカしてたほうが、高頻度な感じでこのみ

じつはpak.nipppnの線路は暗すぎじゃないかと、作った本人もずっと感じていて、過去に明るめの線路も作ったりしたこともあるのですが、あまりよい結果にならなかったので、暗いまま放置してたります。
![lt-track](https://cloud.githubusercontent.com/assets/5622308/10418012/131b79c6-708a-11e5-8327-e0eba55088b1.png)

**Comment by tamaina** [comment]
ご無沙汰です。とある事情で3ヶ月くらいSimutransを放置してました。

> あまりよい結果にならなかった

たしかにコレジャナイ感ありますね・・・大変失礼しました。

高架画像ありがとうございます。お借りします。
受験があるのでだらだら息抜きに作っていきます。

**Comment by tamaina** [comment]
重ね重ねで申し訳ないのですが、上の画像の降雪時画像を頂きたいです。

**Comment by wa-st** [comment]
ご無沙汰してます。

降雪時の画像の画像です、どうぞ。

![elv-frame-back-winter](https://cloud.githubusercontent.com/assets/5622308/12535929/e804650e-c2d7-11e5-944c-87b502d2805a.png) ![elv-frame-center-winter](https://cloud.githubusercontent.com/assets/5622308/12535926/e800151c-c2d7-11e5-905f-ad02b40011f0.png)
![elv-frame-front-winter](https://cloud.githubusercontent.com/assets/5622308/12535927/e80201c4-c2d7-11e5-8932-a1899d7e1bed.png) ![elv-frame-single-winter](https://cloud.githubusercontent.com/assets/5622308/12535928/e802ca6e-c2d7-11e5-9a1d-4d0c701967cc.png)

**Comment by tamaina** [comment]
説明不足で申し訳ないです。
通常の軌道の降雪画像も用意していただけるとありがたいです。

といっても、いまの進捗だと高架にありつけるかさえわかんないんですけどね。

**Comment by wa-st** [comment]
高架の降雪画像だけあっても意味ないですね、すいません。

画像の方ですが、レンダリング結果そのままなので、
PictBearかGimpか何かで調整した方がいいかもしれません。

![track-1-winter](https://cloud.githubusercontent.com/assets/5622308/12872908/31940e42-cdf3-11e5-9057-b841fedc3824.png) ![track-2-winter](https://cloud.githubusercontent.com/assets/5622308/12872905/3191b156-cdf3-11e5-9e20-8538d804a2f1.png)
![track-3-winter](https://cloud.githubusercontent.com/assets/5622308/12872906/31939638-cdf3-11e5-85a1-39dcc6d14a8f.png) ![track-4-winter](https://cloud.githubusercontent.com/assets/5622308/12872907/3193fb0a-cdf3-11e5-8e36-f542f6db66bf.png)

**Comment by soukouki** [comment]
> じつはpak.nipppnの線路は暗すぎじゃないかと

個人的には、低規格の線路が暗いのは、ひっそりと落ち着いた雰囲気があって好きです。

こんな意見もあるということで・・・

**Comment by wa-st** [comment]
ご意見ありがとうございます。

光沢のある物体は、太陽や視点の位置・距離によってガラリと印象が変わるので、
明るい方がいいのかなと思ったり、やっぱり暗くてもいいかなと思いなおしたり、
なかなか表現の難しいところです。
