### ISSUE TITLE
資料写真の送付

### ISSUE THREAD

**Issue by Manche** [wa-st/pak-nippon#6]
初めまして。Mancheと申します。

此度製作の参考になりそうな資料写真がPCの中から見つかりましたのでフォト蔵にupしました。
http://photozou.jp/photo/list/2889699/8791083

蛇足になりますが、現在製作中の箱積み駅舎（昭和前期～中期）です。
クォリティは遠く及びませんが…
![medsh_building](https://cloud.githubusercontent.com/assets/6318189/12596804/11fb997e-c4c5-11e5-9b98-cdb42d6534ef.png)

**Comment by wa-st** [comment]
はじめまして、こんにちは。

たくさんの資料写真ありがとうございます。

それから箱積み駅舎の方ですか、オリジナルの箱積み駅舎は
白一色の素っ気ない駅舎になりがちなので、
様式の違う駅舎というのは、魅力的だと思います。

**Comment by Manche** [comment]
少し古い時代の再現に真っ白の建物は不釣り合いになりますね。
![simscr1559](https://cloud.githubusercontent.com/assets/6318189/12937647/1caca7f8-cfee-11e5-9806-3bc437d15a57.png)
このような昭和初期～中期に建設された（またはその様式）建物の場合だと特に…

![simscr1007](https://cloud.githubusercontent.com/assets/6318189/12937679/75714bdc-cfee-11e5-8fa2-899552cd3253.png)
比較的新しめな建物を再現するのであればデフォルトの方がもってこいな感じがします。
