### ISSUE TITLE
高速道路の制限速度について

### ISSUE THREAD

**Issue by soukouki** [wa-st/pak-nippon#8]
高速道路も対面高速道路も制限速度が100km/hになっていますが、差があったほうが良いのではないでしょうか。

例えば、
対面高速道路の方はそのままで、
（幹線道路の制限速度が70km/hなので、あまり下げると差がなくなってしまう。）
高速道路の制限速度を130km/hくらいに上げるのはどうでしょうか。

**Comment by wa-st** [comment]
130km/hに制限速度を上げてみましたが、どうでしょう？

**Comment by tamaina** [comment]
高速道路、法定的には最高100km/hなんですが......

ゲームバランス的にも実用的にも120km/hくらいに留めておく方が妥当なのではないでしょうか...
あとゲームバランス的にいうと少しは価格が上げた方が良いかもです

対面高速(暫定2車線)の最高速度はだいたい70km/hに設定されているので、同様に+20で90km/hにするとバランスがとれていいかもしれません。

対面高速で100km/hを実現するなら中央はセンターポールではなくガードレール設置の画像を用意するとか(負担かけるようで申し訳ない)。

個人的な要望ですけれど、日本にはない概念なのですが、シムトラ的に160 or 200 or 220km/h道路があると嬉しいです。価格が馬鹿みたいに高くていいので

**Comment by wa-st** [comment]
再び更新して、高速道路は120km/h、対面高速道路は90km/hになりました。

> ゲームバランス的にいうと少しは価格が上げた方が良いかもです

pak.nipponの高速道路は「高速道路」を名乗っていますが、
高速道路以外の使い方（装飾用etc.）も想定しているので、
コストを意図的に甘くしています。

> 160 or 200 or 220km/h道路

way系は絵を描くのに大層手間がかかるので、日本にない道路まで含めた
多彩なラインナップ……などは作る気力が出てこないです。
ごめんなさい。
